lib.callback.register('wx_debug:delete:vehicles', function()
    TriggerClientEvent('wx_debug:delete:vehicles', -1)
end)
lib.callback.register('wx_debug:delete:peds', function()
    TriggerClientEvent('wx_debug:delete:peds', -1)
end)
lib.callback.register('wx_debug:delete:objects', function()
    TriggerClientEvent('wx_debug:delete:objects', -1)
end)
